### ISSUE TITLE
Low-Tech Quarries and Mining Gadgets won't mine

### ISSUE THREAD

**Issue by Jcewazhere** [DoubleNegation/CompactOres#15]
First off thank you for this awesome mod :D

Low-Tech Quarries will remove the block, but what shows up in the chest is an undefined block with a warning texture. With this bug I think it's because that mod is trying to silk touch and retrieve a single block. So it is likely on their end.

Mining gadgets simply won't mine the ores from your mod. I'm not sure why it isn't working, I looked around the configs of both mods and didn't notice anything that would let me fix it myself.

Any help would be appreciated.

**Comment by DoubleNegation** [comment]
The Low-Tech Quarries bug is caused by Low-Tech Quarries incorrectly handling block breaking. The mod doesn't "break" the compact ore at all - it just replaces it with air and drops an item form of the ore - but without any of the state or NBT information, which causes the compact ore to turn into the invalid ore block.  
The mod author [has stated that they are willing to make a change](https://www.curseforge.com/minecraft/mc-mods/low-tech-quarries?comment=14) that would probably fix the compatibility with Compact Ores, so the chances of it getting fixed are looking relatively good.

---
The reason why Mining Gadgets doesn't work is because it simply [refuses to break blocks with Tile Entities](https://github.com/Direwolf20-MC/MiningGadgets/blob/master/src/main/java/com/direwolf20/mininggadgets/common/items/gadget/MiningCollect.java#L80-L83). iirc it has been stated before by the developer of Mining Gadgets that they do not intend to support this due to a range of problems it could cause.  
However, I am planning to stop using Tile Entities in future versions of Compact Ores for other reasons anyway, so this shouldn't be a problem in Minecraft 1.16+.

**Comment by Jcewazhere** [comment]
I got a response from the Mining Gadgets author, sorry I forgot to update here. 
Yay on the low-tech quarries info.
Thank you for your response. :D
