### ISSUE TITLE
port to 1.12.2 

### ISSUE THREAD

**Issue by KiraLinux** [DoubleNegation/CompactOres#2]
can you port your mod to version 1.12.2?

**Comment by DoubleNegation** [comment]
Unfortunately, I am not going to backport compact ores to 1.12.2, or any other previous version, because I believe that the future of modded minecraft lies in future versions. Backporting would therefore be a waste of time that I could have spent improving a mod for a newer version. Also, with all the changes that were made especially during the 1.13 update, 1.12.2 is a very different environment to work with than 1.14.4 in many aspects and backporting would be even more time intensive than it already is anyway.  
If you really need a version for 1.12.2, you could look into using Dense Metals or any other alternative, or you could of course create your own fork of this mod and port it to 1.12.2.
