### ISSUE TITLE
[1.15.2] Fortune not working on custom ores

### ISSUE THREAD

**Issue by Intezium** [DoubleNegation/CompactOres#22]
Forge-31.2.41
CompactOres-2.1.3
AdvancedSwords-0.6.3.5
Ruby and Salt Ore, Fortune 3.
[compactores.zip](https://github.com/DoubleNegation/CompactOres/files/5301426/compactores.zip)

**Comment by DoubleNegation** [comment]
The Ruby and Salt ores from Advanced Swords don't support Fortune in the first place.  
Since Compact Ores only amplifies the existing fortune effect, fortune logically also doesn't work with the compact ores.

You need to report the lack of fortune on the ores to the authors of Advanced Swords to get it fixed. One its fixed in Advanced Swords, the compact ores should automatically also work with fortune.
