### ISSUE TITLE
Crash when another mod errors

### ISSUE THREAD

**Issue by WenXin20** [DoubleNegation/CompactOres#3]
`Minecraft v1.14.4`
`Forge v28.1.109`
`Compact Ores v1.1.2`
`ElecCore v2.0.25`

I get the following crash during launch if the mod ElecCore is installed. [ElecCore](https://www.curseforge.com/minecraft/mc-mods/eleccore) is the mod required for [Crafting Table IV](https://www.curseforge.com/minecraft/mc-mods/craftingtable-iv) to work.
[Crash Report](https://gist.github.com/WenXin20/fc4b174392789fc1a4402af934b85239)

**Comment by DoubleNegation** [comment]
After doing a bit of investigation, I found out that, as far as I can tell, this crash is not caused by Compact Ores, nor is there something that I can do to fix it.  
It seems that ElecCore, when combined with some other mod - I do not know which mod - crashes in synchronous work after the `CONSTRUCT` phase. For some reason, after that error, the game moves on to resource loading (instead of crashing or moving on with mod loading). Then, in the resource loading process, it is just a question of time until another mod crashes the game by trying to access some data that never got initialized. In the case of your modpack, Compact Ores is simply the first mod to do this by coincidence - try removing it and some other mod will cause a similar crash.

I might be wrong with this analysis, as my crash report looks slightly different from yours, so please report back once you have tried launching without Compact Ores.

**Comment by WenXin20** [comment]
Alright, thanks, I'll try that out.

**Comment by WenXin20** [comment]
You're right, I got a crash even without Compact Ores. Thanks for the help!

**Comment by WenXin20** [comment]
I also noticed that the Inspirations mod also had an error, but for some reason Compact Ores gave me the same crash report as the one above. I'm wondering if this mod isn't closing down proper when other mods produce an error.

**Comment by WenXin20** [comment]
This crash still can happen without ElecCore. I discovered that it happens if another mod has an error, such as with a config file, then this mod will crash instead of displaying the forge screen of what went wrong.

**Comment by DoubleNegation** [comment]
I think I have finally figured this out:  
If a mod crashes during `CONSTRUCT`, forge skips any further loading of mods or registries or anything really, and moves on to resource loading so it can display the error screen. During resource loading, however, the compact ores resource pack tries to initialize, crashing the game. So the fix would be not loading compact ore resources if mod loading never _really_ happened.  
Fix incoming...
